# Generated by Django 2.1.4 on 2019-01-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO portal_sandbstatic (id, name, sandb_static) VALUES (1,	'Description',	'Describe your Cloud'),(2,	'Tos',	'Add your Terms Of Service'), (3,	'HomeStatic',	'Add Default home page text');"
        )
    ]
