version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - automerge
  ignore:
  - dependency-name: phonenumbers
    versions:
    - 8.12.17
    - 8.12.18
    - 8.12.19
    - 8.12.20
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
