name: Usery Integration Tests

on: [push]
# on:
#   pull_request:
#     branches:
#     - master
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:19.6
        env:
          POSTGRES_USER: useryuser
          POSTGRES_PASSWORD: userypassword
          POSTGRES_DB: userydb
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      working-directory: ./postgres
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./postgres
    - name: Create env file
      run: |
        mv .env.ci .env
        echo DATABASE_PORT=${{ job.services.postgres.ports[5432] }}
    - name: Run non DB tests
      run: |
        python manage.py test
    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pip install pytest
    #     pytest

